project:
  type: website
  output-dir: docs

website:
  title: "body and bytes"
  navbar:
    right:
      # - href: index.qmd
      #   text: Home
      - href: blogs.qmd
        text: Blog
      # - about.qmd
      # - href: body.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
