project:
  type: website
  output-dir: docs

website:
  title: "Mrigank's blog"
  navbar:
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    # mainfont: georgia
    css: styles.css
    toc: true
