project:
  type: website
  output-dir: docs

website:
  title: "Rewire"
  navbar:
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    mainfont: lora
    css: styles.css
    toc: true
    fontsize: 1.3em