project:
  type: website
  output-dir: docs

website:
  title: "body bytes"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: blogs.qmd
        text: Blog
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
